# Generated by Django 6.0.4 on 2026-04-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('creator', 'Creator')], db_index=True, default='user', max_length=20),
        ),
    ]
