# Generated by Django 6.0.4 on 2026-04-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorapplication',
            name='mobile_number',
            field=models.CharField(blank=True, default='', help_text="Applicant's mobile number", max_length=20),
        ),
        migrations.AddField(
            model_name='creatorapplication',
            name='primary_platform_link',
            field=models.URLField(blank=True, default='', help_text="Link to the applicant's primary social/content platform"),
        ),
        migrations.AddField(
            model_name='creatorapplication',
            name='selfie',
            field=models.ImageField(blank=True, help_text="Applicant's selfie for identity verification", null=True, upload_to='creator_applications/selfies/'),
        ),
        migrations.AddField(
            model_name='creatorapplication',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', help_text="Applicant's WhatsApp number (if different from mobile)", max_length=20),
        ),
    ]
