# Generated by Django 6.0.4 on 2026-04-19 21:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='rooms/covers/')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='creator.creatorprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='community_r_slug_3ad221_idx'), models.Index(fields=['is_active'], name='community_r_is_acti_ba2367_idx')],
            },
        ),
    ]
