name: Deploy Production

on:
  push:
    branches: ["main"]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: copy compose file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SSH_USER }}/dailo-backend/"

      - name: deploy server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/dailo-backend

            git pull origin main

            echo "ENVIRONMENT=prod" > .env
            echo "DEBUG=False" >> .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
            echo "ALLOWED_HOSTS=*" >> .env

            echo "DATABASE_URL=postgresql://postgres:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}" >> .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env

            echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> .env
            echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> .env
            echo "EMAIL_USE_TLS=${{ secrets.EMAIL_USE_TLS }}" >> .env
            echo "EMAIL_USE_SSL=${{ secrets.EMAIL_USE_SSL }}" >> .env
            echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> .env
            echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env
            echo "DEFAULT_FROM_EMAIL=${{ secrets.DEFAULT_FROM_EMAIL }}" >> .env

            echo "CELERY_BROKER_URL=redis://redis:6379/0" >> .env
            echo "CELERY_RESULT_BACKEND=redis://redis:6379/0" >> .env

            echo "CLOUD_NAME=${{ secrets.CLOUD_NAME }}" >> .env
            echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
            echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
            echo "CLOUDINARY_WEBHOOK_SECRET=${{ secrets.CLOUDINARY_WEBHOOK_SECRET }}" >> .env

            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
            echo "AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }}" >> .env
            echo "AWS_S3_ENDPOINT_URL=${{ secrets.AWS_S3_ENDPOINT_URL }}" >> .env
            echo "MEDIA_URL=${{ secrets.MEDIA_URL }}" >> .env

            docker compose -f docker-compose.yml build
            docker compose -f docker-compose.yml up -d --remove-orphans

            docker compose -f docker-compose.yml exec -T web python manage.py migrate
            docker compose -f docker-compose.yml exec -T web python manage.py collectstatic --noinput

            docker image prune -f

            echo "DEPLOY SUCCESS"
